【問題1】行列積を手計算する

In [ ]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

-1*0 + 2*0 + 3*2    -1*2 + 2*2 + 3*9   -1*1 + 2*-8 + 3*-1
4*0 + -5*0 + 6*2   4*2 + -5*2 + 6*9   4*1 + -5*-8 + 6*-1
7*0 + 8*0 + -9*2   7*2 + 8*2 + -9*9.  7*1 + 8*-8 + -9*-1

   6   29   -20
 12   52    38
-18  -51   -48

【問題2】NumPyの関数による計算

In [1]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

c_ndarray = np.matmul(a_ndarray,b_ndarray)

print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [2]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

d_ndarray = np.dot(a_ndarray,b_ndarray)

print(d_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装

In [6]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ans = 0

for i in range(0,3):
    ans1 = a_ndarray[0,i]*b_ndarray[i,0]
    ans += ans1
    
print(ans)

6


【問題4】行列積を行う関数の作成

In [5]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def multi(a,b):
    
    ans = np.zeros((len(a),len(b[0])))
    ii = len(a)
    kk = len(b)
    jj = len(b[0])

    for i in range(ii):
        for j in range(jj):
            for k in range(kk):
                ans[i][j] = ans[i][j] + a[i][k]*b[k][j]
        
    return ans

print(multi(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


【問題5】計算が定義されない入力を判定する

In [7]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def multi(a,b):

    ans = np.zeros((len(a),len(b[0])))
    
    ii = len(a)
    kk = len(b)
    jj = len(b[0])
    if len(a[0]) != len(b):　　　　#aの0行とbの[0]行が一致しなければエラー表示
        print("配列に問題あり、計算できません！")
    else:
        print(ii,kk,jj)
        for i in range(ii):
            for j in range(jj):
                for k in range(kk):
                    ans[i][j] = ans[i][j] + a[i][k]*b[k][j]

        return ans

print(multi(d_ndarray,e_ndarray))


配列に問題あり、計算できません！
None


【問題6】転置

In [8]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
f_ndarray = np.transpose(e_ndarray)
g_ndarray = e_ndarray.T
#print(f_ndarray)           確認用
#print(g_ndarray)          確認用

def multi(a,b):

    ans = np.zeros((len(a),len(b[0])))
    
    ii = len(a)
    kk = len(b)
    jj = len(b[0])
    if len(a[0]) != len(b):
        print("配列に問題あり、計算できません！")
    else:
        #print(ii,kk,jj)
        for i in range(ii):
            for j in range(jj):
                for k in range(kk):
                    ans[i][j] = ans[i][j] + a[i][k]*b[k][j]

        return ans

print(multi(d_ndarray,f_ndarray))
print(multi(d_ndarray,g_ndarray))

[[ 46.  -4.]
 [-34.  73.]]
[[ 46.  -4.]
 [-34.  73.]]
